#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

menu_prompt = <<EOS
1. Add a goal
2. List all goals
3. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  choose do |menu|
    menu.prompt = ""

    goals_controller = GoalsController.new
    menu.choice('Add a goal') { say("") }
    menu.choice('List all goals') { goals_controller.index }
    menu.choice('Exit') { say("Good luck, see you soon!\n") }
  end
else
  puts "[Help] Run as: ./sleep_tracker manage"
end