#!/usr/bin/env ruby
require 'highline/import'

menu_prompt = <<EOS
1. Add a goal
2. List all gaossss
3. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
    choose do |menu|
      menu.prompt = ""

      menu.choice('Add a goal') { say("") }
      menu.choice('List all goals') { say("No goals found. Add a goal.\n") }
      menu.choice('Exit') { say("Good luck, see you soon!\n") }
    end
else
  puts "[Help] Run as: ./sleep_tracker manage"
end