#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each { |f| require f }
Dir["./lib/*.rb"].each { |f| require f }

menu_prompt = <<EOS
1. Add a goal
2. List all goals
3. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  loop do
    choose do |menu|
      menu.prompt = ""

      goals_controller = GoalsController.new
      menu.choice('Add a goal') do
        user_input = ask("What goal would you like to add?")
        response = goals_controller.add(user_input)
        say("\"#{user_input}\" has been added\n") unless response.nil?
      end
      menu.choice('List all goals') do
        say(goals_controller.index)
        exit
      end
      menu.choice('Exit') do
        say("Good luck, see you soon!\n")
        exit
      end
    end
  end
else
  puts "[Help] Run as: ./sleep_tracker manage"
end